---

- name: Install dependencies
  apt: name=python-pip
  when: ansible_os_family == 'Debian'

- name: Install supervisor
  pip: name=supervisor version={{ supervisor_version }}
  notify:
    - restart {{ supervisord_instance_name }}

- name: Install superlance
  pip: name=superlance
  when: supervisor_superlance

- name: Prepare directories
  file: state=directory path={{item}}
  with_items:
    - "{{ supervisord_conf_dir }}"
    - "{{ supervisord_conf_include_dir }}"
    - "{{ supervisord_log_dir }}"

- name: Create init script
  template: src=upstart.j2 dest=/etc/init/{{ supervisord_instance_name }}.conf owner=root group=root mode=0644
  notify:
    - restart {{ supervisord_instance_name }}

- name: Create configuration
  template: src=supervisord.conf.j2 dest={{ supervisord_conf_file }} owner=root group=root mode=0644
  notify:
    - reload {{ supervisord_instance_name }}

- name: Start {{ supervisord_instance_name }} with system
  service: name={{ supervisord_instance_name }} state=started enabled=yes
